In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [3]:
nnfs.init()

In [4]:
class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [5]:
class ActivationReLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)

In [6]:
class ActivationLinear:
    def forward(self, inputs):
        self.outputs = inputs

In [7]:
X, y = spiral_data(samples=100, classes=3)
dense1 = LayerDense(2, 3)
dense1.forward(X)
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


In [8]:
activation1 = ActivationReLU()
activation1.forward(dense1.output)
print(activation1.outputs[:5])

[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]


In [12]:
dense2 = LayerDense(3,3)
dense2.forward(activation1.outputs)
print(dense2.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 6.9092300e-07 -2.0009008e-06  5.1385609e-07]
 [ 1.9238005e-06 -5.5712917e-06  1.4307767e-06]
 [ 3.1932580e-06 -9.2476184e-06  2.3749030e-06]
 [ 4.3292066e-06 -1.2537305e-05  3.2197354e-06]]


In [13]:
activation2 = ActivationLinear()
activation2.forward(dense2.output)
print(activation2.outputs[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 6.9092300e-07 -2.0009008e-06  5.1385609e-07]
 [ 1.9238005e-06 -5.5712917e-06  1.4307767e-06]
 [ 3.1932580e-06 -9.2476184e-06  2.3749030e-06]
 [ 4.3292066e-06 -1.2537305e-05  3.2197354e-06]]
