In [1]:
import numpy as np

In [4]:
inputs = [
    [0.54, 0.31, 0.33, 0.62, 0.31],
    [0.41, 0.62, 0.12, 0.2, 0.99],
    [0.49, 0.64, 0.77, 0.22, 0.11],
    [0.66, 0.1, 0.44, 0.31, 0.72]
] # 5x4
weights = [
    [0.82, 0.65, 0.68, 0.99, 0.37],
    [0.90, 0.30, 0.65, 0.83, 0.89],
    [0.66, 0.52, 0.76, 0.76, 0.12],
    [0.16, 0.32, 0.06, 0.79, 0.53]
] # 5x4

biases = [0.54, 0.31, 0.73, 0.44]

inputs = np.array(inputs)
weights = np.array(weights).T

results = np.dot(inputs, weights) + biases
print(results)

[[2.1372 1.894  2.0068 1.2995]
 [1.9251 1.9901 1.685  1.3939]
 [2.1399 1.724  2.1518 1.0015]
 [2.0187 2.1181 1.874  1.2305]]


In [8]:
weights2 = [
    [0.03, 0.34, 0.54, 0.05],
    [0.04, 0.15, 0.61, 0.62],
    [0.43, 0.75, 0.07, 0.86],
    [0.33, 0.57, 0.7, 0.68]
]
biases2 = [
    [0.48, 0.93, 0.77, 0.55],
    [0.76, 0.11, 0.05, 0.20],
    [0.88, 0.51, 0.46, 0.64],
    [0.16, 0.05, 0.64, 0.66],
]

weights2 = np.array(weights2)
result2 = np.dot(results, weights2) + biases2

print(result2)

arr = np.array([1,2,3])
arr.shape

[[1.911635 4.186563 4.129554 4.440648]
 [2.081894 3.121322 3.397195 3.927069]
 [2.268926 3.680871 3.518862 4.347443]
 [1.51717  3.160958 4.014669 4.522537]]
