In [2]:
import numpy as np

In [17]:
inputs = [
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
]

weights = [
    [1, 3],
    [2, 5],
    [3, 7],
    [4, 9]
]

biases = [0,0,0,0]

inputs = np.array(inputs)
weights = np.array(weights).T

print("WEIGHT TRANSPOSE")
print(weights)

print("----------")

results = np.dot(inputs, weights) + biases
print(results)


# 4 inputa
# 1 hidden
# 4 outputa



WEIGHT TRANSPOSE
[[1 2 3 4]
 [3 5 7 9]]
----------
[[ 7 12 17 22]
 [11 19 27 35]
 [15 26 37 48]
 [19 33 47 61]]
