In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [3]:
nnfs.init()

In [4]:
class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [7]:
class ActivationReLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)

In [38]:
X, y = spiral_data(samples=100, classes=3)
dense1 = LayerDense(2, 3)
dense1.forward(X)
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-3.3586264e-05 -2.6227324e-05  1.5658256e-06]
 [-7.8423065e-05 -4.4464159e-05  2.4120887e-05]
 [-6.9194612e-05 -7.9462952e-05 -2.7794827e-05]
 [-1.5983211e-04 -7.4782925e-05  6.8481160e-05]]


In [44]:
activation1 = ActivationReLU()
activation1.forward(dense1.output)
print(activation1.outputs[:5])

[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.5658256e-06]
 [0.0000000e+00 0.0000000e+00 2.4120887e-05]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 6.8481160e-05]]
